### ISSUE TITLE
IT : Sabertooth

### ISSUE THREAD

**Issue by AlexBevilacqua** [dododex/translations#108]
Sabertooth it's translated as "Smilodonte" in Dododex, this quite inconvenient because the ingame name is displayed as "Tigre dai denti a sciabola".. at least on PS4, last version.
Took me very long time to figure this out, I was assuming it was missing till today.

If the translation is good accordingly to other versions of the game, I can now live with it, close the issue :)

Just wanted to let you know this small thing.. and thank you for the great job!

**Comment by danleveille** [comment]
@AlexBevilacqua Thank you! I just fixed this translation. 

Since Dododex is translated by volunteers, there's only a few people (sometimes just one) translating each language. If you spot any other errors, please feel free to open another ticket. Or, it's very easy to edit the file yourself, too: [https://github.com/dododex/translations/blob/master/creatures.json](creatures.json)
