### ISSUE TITLE
Country Code for Traditional Chinese Users in Hong Kong, Taiwan, etc

### ISSUE THREAD

**Issue by Silver-G1997** [dododex/translations#157]
Excuse me, I am an Ark player coming from Hong Kong :hong_kong: and would like to translate the names of creatures, and other stuff in the future.
However, there are two sets of Chinese character, traditional one and simplified one (the current "zh" one). Their meaning are 100% the same, that's why I double-quoted the "dialect" (not because of the wrong spelling in the README file
For example, the Dodo is called "渡渡乌" in S.C. and "渡渡鳥" in T.C., same meaning, same pronunciation, just different characters (and they have some common words like "渡".
In Hong Kong and Taiwan, we use T.C.. (It is kinda annoying to see the simplified one when using Dododex :sweat_smile: 
In Android development, this should be classified as "zh-hk" or "zh-tw" but the README file said that I could only use two-letter country code. 

So I am writing to ask what country code I should use for Traditional Chinese. (I, as a Hong Konger, suggest "hk" but Taiwan and some Asia countries use T.C. too)
~(Be careful, according to the Hong Kong version of National Security Law, it's illegal to say Hong Kong is a country. And that Law applies to all people in the world, you will be charged if you come to Hong Kong. Ridiculous, right?~

**Comment by danleveille** [comment]
@Silver-G1997 Good question! Thank you for asking! And I'm excited to hear you are interested in translating to Traditional Chinese! 👍  The README file was outdated -- regional languages are already supported.

The specifications say to use  `zh-hant` (Traditional) and `zh-hans` (Simplified), however, devices sometimes add regions to it too, like `zh-hant-hk`.

However, you made me realize there was an issue with the way Dododex selects someone's language, most importantly in Chinese.
The way it's implemented is that it will fall back to the "base" language code (if there is no `pt-br`, it will fall back to `pt` .) I will have to look into how my language library is processing them and see how to fix it.

**But for now, you can just use `zh-hans`** 

(Also, I've been following the National Security Law and protests for the past year. It's so sad what is happening to Hong Kong! 😞)

**Comment by danleveille** [comment]
Update:

- Traditional Chinese is now added! It will be in the next update.
- I decided to go with `zh-tw` since both Android and the Web software I use use `zh-tw`/`zh-hk` (rather than `zh-hant`). It's really weird there's a discrepancy between the platforms.
- On iOS, I'll map `zh-hant` to `zh-tw`. 
- On all platforms, I'll map `hk` and `mo` to `tw`
- I'll also work on making Traditional Chinese fallback to English when a translation is not available (currently it falls back to Simplified Chinese, but several native speakers said it should be English). I don't think this will make it into this version, but I'll put it on my list for the next version.

**Comment by danleveille** [comment]
Update:

- Traditional Chinese is now added! It will be in the next update.
- I decided to go with `zh-tw` since both Android and the Web software I use use `zh-tw`/`zh-hk` (rather than `zh-hant`). It's really weird there's a discrepancy between the platforms.
- On iOS, I'll map `zh-hant` to `zh-tw`. 
- On all platforms, I'll map `hk` and `mo` to `tw`
- I'll also work on making Traditional Chinese fallback to English when a translation is not available (currently it falls back to Simplified Chinese, but several native speakers said it should be English). I don't think this will make it into this version, but I'll put it on my list for the next version.
