### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by Runofhope** [dododex/translations#63]
Hello! Im just curious about this app and im a big fan of the game! Im willing to help you out with a translation into swedish if thats not done already. Have a nice day and thanks for a great app.

**Comment by danleveille** [comment]
@Runofhope Please do! Thank you so much for offering. Swedish hasn't been translated yet. 😄

**Comment by danleveille** [comment]
@Runofhope Just merged this! Thank you so much!

Quick question. I've added one more term: "Qty" (abbreviated form of "quantity.") 

Is "Kvantitet" the correct word to use for quantity? And if so, is there an abbreviated form? (Just because the space is limited, and this is a prominent translation.)

**Comment by Runofhope** [comment]
Hey Dan!

I would rather use the word "Antal",
abbreviated "st." (Stycken) meaning "Pieces"

Have a good one!

Best regards,

David
________________________________

**Comment by danleveille** [comment]
@Runofhope! Thanks so much! Would have never figured that out on my own! :P
