### ISSUE TITLE
Anglicisms

### ISSUE THREAD

**Issue by Nest0r13** [dododex/translations#8]
Hello,

My name is Nestor and I'm trying to help in the translated into Spanish .
In Spain the people use a lot of anglicisms in ark . For example

English : Spanish : Anglicism
Taming : Taming : Tamear
Server : Servidor : Server
Crafting : Fabricar : Craftear
level : nivel : level

Dont exist a word for Starving, the most similar is "hambre" but means hungry , not starving

And Kibble in  the translation of the game they use the word "croqueta" thant means Croquette, and i think that is better use "Pienso" that is animal feed (Dogs,cats,etc)

I need advice.
Thanks

**Comment by danleveille** [comment]
@Nest0r13 Thanks for asking! You know the language better than me, so If the anglicisms make more sense and are clearer to users rather than the Spanish versions of the word, please use those versions. :)

For "Starving", feel free to use whichever word makes the most sense. If the English version is more appropriate, you're welcome to use that.

The goal is to make the app understandable for people who speak Spanish, so whatever is the most appropriate term. :)

Thanks!

**Comment by BiGR1pp3r** [comment]
@Nest0r13,
" Starving " es una expresión para "muerto de hambre". Puede utilizar " hambriento ".

**Comment by danleveille** [comment]
@Nest0r13 Heya! If you've done any Spanish translations so far, would you be able to post them to Github? Just because there's another person who is going to start on some of the Spanish translations tomorrow. If you haven't done any, no worries, I just didn't want you to waste your time. :)
